### ISSUE TITLE
Hyrule Warriors Age of Calamity - LinkData.bin

### ISSUE THREAD

**Issue by timartinelli** [Raytwo/feth-archive-manager#1]
Friend is it possible for you to add support for this file?

https://drive.google.com/file/d/1FqA42xKYFc0kQ0WQ1_fHM0SCxy76xeLK/view?usp=sharing

I am part of a group in Brazil that I want to translate this Zelda game.

**Comment by Raytwo** [comment]
Hey there, extremely sorry for the long delay but this project isn't maintained anymore and you shouldn't use it for your own good.
Consider using [that](https://github.com/three-houses-research-team/THAT) instead.
